version: "3.1"
services:
  # mongo:
  #   image: 'mongo:latest'
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: mongoPassword
  server:
    build:
      context: ./server
    ports:
      - '5000:5000'
    volumes:
      - /app/node_modules
      - ./server:/app
    # depends_on:
    #   - mongo
  client:
    build:
      context: ./client
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - server